export const GET_PARTY_PENDING = "GET_PARTY_PENDING";
export const GET_PARTY_SUCCESS = "GET_PARTY_SUCCESS";
export const GET_PARTY_ERROR = "GET_PARTY_ERROR";

export const POST_PARTY_PENDING = "POST_PARTY_PENDING";
export const POST_PARTY_SUCCESS = "POST_PARTY_SUCCESS";
export const POST_PARTY_ERROR = "POST_PARTY_ERROR";

export const DELETE_PARTY_PENDING = "DELETE_PARTY_PENDING";
export const DELETE_PARTY_SUCCESS = "DELETE_PARTY_SUCCESS";
export const DELETE_PARTY_ERROR = "DELETE_PARTY_ERROR";

// VOTER

export const GET_USER_PENDING = "GET_USER_PENDING";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const POST_USER_PENDING = "POST_USER_PENDING";
export const POST_USER_SUCCESS = "POST_USER_SUCCESS";
export const POST_USER_ERROR = "POST_USER_ERROR";

export const DELETE_USER_PENDING = "DELETE_USER_PENDING";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

//ELECTION

export const GET_ELECTION_PENDING = "GET_ELECTION_PENDING";
export const GET_ELECTION_SUCCESS = "GET_ELECTION_SUCCESS";
export const GET_ELECTION_ERROR = "GET_ELECTION_ERROR";

export const POST_ELECTION_PENDING = "POST_ELECTION_PENDING";
export const POST_ELECTION_SUCCESS = "POST_ELECTION_SUCCESS";
export const POST_ELECTION_ERROR = "POST_ELECTION_ERROR";

export const DELETE_ELECTION_PENDING = "DELETE_ELECTION_PENDING";
export const DELETE_ELECTION_SUCCESS = "DELETE_ELECTION_SUCCESS";
export const DELETE_ELECTION_ERROR = "DELETE_ELECTION_ERROR";

//PARTY CONNECTION

export const GET_PARTY_CONNECTION_PENDING = "GET_PARTY_CONNECTION_PENDING";
export const GET_PARTY_CONNECTION_SUCCESS = "GET_PARTY_CONNECTION_SUCCESS";
export const GET_PARTY_CONNECTION_ERROR = "GET_PARTY_CONNECTION_ERROR";

export const POST_PARTY_CONNECTION_PENDING = "POST_PARTY_CONNECTION_PENDING";
export const POST_PARTY_CONNECTION_SUCCESS = "POST_PARTY_CONNECTION_SUCCESS";
export const POST_PARTY_CONNECTION_ERROR = "POST_PARTY_CONNECTION_ERROR";

export const DELETE_PARTY_CONNECTION_PENDING = "DELETE_PARTY_CONNECTION_PENDING";
export const DELETE_PARTY_CONNECTION_SUCCESS = "DELETE_PARTY_CONNECTION_SUCCESS";
export const DELETE_PARTY_CONNECTION_ERROR = "DELETE_PARTY_CONNECTION_ERROR";

// VOTE

export const GET_VOTE_PENDING = "GET_VOTE_PENDING";
export const GET_VOTE_SUCCESS = "GET_VOTE_SUCCESS";
export const GET_VOTE_ERROR = "GET_VOTE_ERROR";

export const POST_VOTE_PENDING = "POST_VOTE_PENDING";
export const POST_VOTE_SUCCESS = "POST_VOTE_SUCCESS";
export const POST_VOTE_ERROR = "POST_VOTE_ERROR";

export const DELETE_VOTE_PENDING = "DELETE_VOTE_PENDING";
export const DELETE_VOTE_SUCCESS = "DELETE_VOTE_SUCCESS";
export const DELETE_VOTE_ERROR = "DELETE_VOTE_ERROR";

